/**
 * @author Kelompok 2 - R6P
 */

package GUI;
import SYNTAX.BRG_MASUK;
import SYNTAX.KONEKSI;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class BARANG_MASUK extends javax.swing.JFrame {
    DASHBOARD board = new DASHBOARD();
    
    public BARANG_MASUK() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tabel_brg.getTableHeader().setOpaque(false);
        tabel_brg.getTableHeader().setBackground(new java.awt.Color(43, 57, 144));
        tabel_brg.getTableHeader().setForeground(java.awt.Color.BLACK);
        tabel_brg.getTableHeader().setFont(new java.awt.Font("Sans Serif", java.awt.Font.BOLD, 14));
        tabel_brg.getTableHeader().setReorderingAllowed(false);
    }
    
    public void refreshTable (){
        int selectedRow = tabel_brg.getSelectedRow();
        
        String nama = input_namabrg.getText();
        String kategori = (String) cmb_kategori.getSelectedItem();
        int jumlah = (int) spin_jumlah.getValue();
        
        DefaultTableModel model = (DefaultTableModel) tabel_brg.getModel();
        model.setValueAt(nama, selectedRow, 1);     // Kolom ke-1: Nama Barang
        model.setValueAt(kategori, selectedRow, 2); // Kolom ke-2: Kategori
        model.setValueAt(jumlah, selectedRow, 3);   // Kolom ke-3: Jumlah
    }
    
    public void resetData(){
        input_namabrg.setText("");
        spin_jumlah.setValue(1);
    }
    
    public String generateIdBarang() {
        String newId = "BRG001";

        try {
            Connection conn = KONEKSI.getConnection();
            String query = "SELECT id_barang FROM barang ORDER BY id_barang DESC LIMIT 1";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String lastId = rs.getString("id_barang"); // ex: "BRG004"
                int number = Integer.parseInt(lastId.substring(3)); // ambil angka: 4
                number++; // jadi 5
                newId = String.format("BRG%03d", number); // jadi "BRG005"
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    
        return newId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        Label_masuk = new javax.swing.JLabel();
        Label_idbrg = new javax.swing.JLabel();
        tampil_idbrg = new javax.swing.JLabel();
        Label_namabrg = new javax.swing.JLabel();
        input_namabrg = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Label_kategori = new javax.swing.JLabel();
        cmb_kategori = new javax.swing.JComboBox<>();
        Label_jumlah = new javax.swing.JLabel();
        spin_jumlah = new javax.swing.JSpinner();
        btn_SAVE = new javax.swing.JButton();
        btn_EDIT = new javax.swing.JButton();
        btn_DELETE = new javax.swing.JButton();
        Main_menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_brg = new javax.swing.JTable();
        btn_BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar.setPreferredSize(new java.awt.Dimension(300, 600));

        Label_masuk.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Label_masuk.setForeground(new java.awt.Color(255, 255, 255));
        Label_masuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_masuk.setText("BARANG MASUK");

        Label_idbrg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Label_idbrg.setForeground(new java.awt.Color(255, 255, 255));
        Label_idbrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_idbrg.setText("ID Barang");

        tampil_idbrg.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tampil_idbrg.setForeground(new java.awt.Color(255, 255, 255));

        Label_namabrg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Label_namabrg.setForeground(new java.awt.Color(255, 255, 255));
        Label_namabrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_namabrg.setText("Nama Barang");

        input_namabrg.setBackground(new java.awt.Color(43, 57, 144));
        input_namabrg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        input_namabrg.setForeground(new java.awt.Color(255, 255, 255));
        input_namabrg.setBorder(null);

        Label_kategori.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Label_kategori.setForeground(new java.awt.Color(255, 255, 255));
        Label_kategori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_kategori.setText("Kategori");

        cmb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karbohidrat", "Protein Nabati", "Protein Hewani", "Buah", "Minuman" }));

        Label_jumlah.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Label_jumlah.setForeground(new java.awt.Color(255, 255, 255));
        Label_jumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_jumlah.setText("Jumlah");

        btn_SAVE.setBackground(new java.awt.Color(155, 169, 255));
        btn_SAVE.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_SAVE.setForeground(new java.awt.Color(255, 255, 255));
        btn_SAVE.setText("SAVE");
        btn_SAVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SAVEActionPerformed(evt);
            }
        });

        btn_EDIT.setBackground(new java.awt.Color(155, 169, 255));
        btn_EDIT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_EDIT.setForeground(new java.awt.Color(255, 255, 255));
        btn_EDIT.setText("EDIT");
        btn_EDIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EDITActionPerformed(evt);
            }
        });

        btn_DELETE.setBackground(new java.awt.Color(255, 102, 102));
        btn_DELETE.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_DELETE.setForeground(new java.awt.Color(255, 255, 255));
        btn_DELETE.setText("DELETE");
        btn_DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DELETEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SidebarLayout.createSequentialGroup()
                                .addComponent(btn_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SidebarLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btn_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SidebarLayout.createSequentialGroup()
                                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Label_namabrg)
                                        .addComponent(Label_idbrg)
                                        .addComponent(Label_kategori)
                                        .addComponent(input_namabrg, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(Label_jumlah)
                                        .addComponent(jSeparator1))
                                    .addComponent(spin_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tampil_idbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Label_masuk)))
                .addGap(28, 28, 28))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Label_masuk)
                .addGap(34, 34, 34)
                .addComponent(Label_idbrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tampil_idbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(Label_namabrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_namabrg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Label_kategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_jumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spin_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Main_menu.setBackground(new java.awt.Color(155, 169, 255));

        tabel_brg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tabel_brg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Kategori", "Jumlah"
            }
        ));
        tabel_brg.setRowHeight(30);
        tabel_brg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_brgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_brg);

        btn_BACK.setBackground(new java.awt.Color(43, 57, 144));
        btn_BACK.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_BACK.setForeground(new java.awt.Color(255, 255, 255));
        btn_BACK.setText("BACK");
        btn_BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BACKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Main_menuLayout = new javax.swing.GroupLayout(Main_menu);
        Main_menu.setLayout(Main_menuLayout);
        Main_menuLayout.setHorizontalGroup(
            Main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_menuLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(Main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        Main_menuLayout.setVerticalGroup(
            Main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_menuLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        getContentPane().add(Main_menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SAVEActionPerformed
        String id = generateIdBarang();
        String nama = input_namabrg.getText();
        String kategori = (String) cmb_kategori.getSelectedItem();
        int jumlah = (int) spin_jumlah.getValue();

        if (!nama.isEmpty() && jumlah != 0) {
            DefaultTableModel model = (DefaultTableModel) tabel_brg.getModel();
            boolean add = BRG_MASUK.save(id, nama, kategori, jumlah);
            
            if (add){
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
                model.addRow(new Object[]{id, nama, kategori, jumlah});
            } else {
                JOptionPane.showMessageDialog(this, "Gagal Menyimpan data");
            }
            
            resetData();
        } else {
            JOptionPane.showMessageDialog(this, "Masukkan data yang valid!");
        }
    }//GEN-LAST:event_btn_SAVEActionPerformed

    private void btn_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EDITActionPerformed
        int selectedRow = tabel_brg.getSelectedRow();
        
        String id = tabel_brg.getValueAt(selectedRow, 0).toString();            
        String nama = input_namabrg.getText();
        String kategori = (String) cmb_kategori.getSelectedItem();
        int jumlah = (int) spin_jumlah.getValue();
        
            if(selectedRow != -1){
                boolean isUpdated = BRG_MASUK.edit(id, nama, kategori, jumlah);

                if(isUpdated){   
                    JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                    refreshTable();
                    resetData();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal mengubah data");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris di tabel yang ingin diubah terlebih dahulu");
            }
    }//GEN-LAST:event_btn_EDITActionPerformed

    private void btn_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DELETEActionPerformed
        int selectedRow = tabel_brg.getSelectedRow();

        if (selectedRow != -1){
            String id = tabel_brg.getValueAt(selectedRow, 0).toString();
            String nama = tabel_brg.getValueAt(selectedRow, 1).toString();

            int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin ingin menghapus " + nama + "?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if(confirm == JOptionPane.YES_OPTION){
                boolean isDeleted = BRG_MASUK.delete(id);

                if (isDeleted){
                    DefaultTableModel model = (DefaultTableModel) tabel_brg.getModel();
                    model.removeRow(selectedRow);

                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    resetData();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data dari database!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris di tabel yang ingin di hapus terlebih dahulu!");
        }
    }//GEN-LAST:event_btn_DELETEActionPerformed

    private void tabel_brgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_brgMouseClicked
        int baris = tabel_brg.getSelectedRow();
    
        tampil_idbrg.setText(tabel_brg.getValueAt(baris, 0).toString());
        input_namabrg.setText(tabel_brg.getValueAt(baris, 1).toString());
        cmb_kategori.setSelectedItem(tabel_brg.getValueAt(baris, 2).toString());
        spin_jumlah.setValue(Integer.parseInt(tabel_brg.getValueAt(baris, 3).toString()));
    }//GEN-LAST:event_tabel_brgMouseClicked

    private void btn_BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BACKMouseClicked
        board.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BACKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BARANG_MASUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BARANG_MASUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BARANG_MASUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BARANG_MASUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BARANG_MASUK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_idbrg;
    private javax.swing.JLabel Label_jumlah;
    private javax.swing.JLabel Label_kategori;
    private javax.swing.JLabel Label_masuk;
    private javax.swing.JLabel Label_namabrg;
    private javax.swing.JPanel Main_menu;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JButton btn_BACK;
    private javax.swing.JButton btn_DELETE;
    private javax.swing.JButton btn_EDIT;
    private javax.swing.JButton btn_SAVE;
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JTextField input_namabrg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spin_jumlah;
    private javax.swing.JTable tabel_brg;
    private javax.swing.JLabel tampil_idbrg;
    // End of variables declaration//GEN-END:variables
}
