/**
 * @author Wijdan Afifi
 */

package GUI;
import SYNTAX.KONEKSI;
import SYNTAX.MENU;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.*;
import java.awt.Color;

public class DASHBOARD extends javax.swing.JFrame {
    MENU board = new MENU();
    /**
     * Creates new form DASHBOARD
     */
    public DASHBOARD() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tabel_brg.setModel(board.getModelBarang());
        tabel_brg.getTableHeader().setOpaque(false);
        tabel_brg.getTableHeader().setBackground(new java.awt.Color(43, 57, 144));
        tabel_brg.getTableHeader().setForeground(java.awt.Color.BLACK);
        tabel_brg.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tabel_brg.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        pn_profil = new javax.swing.JPanel();
        Label_profil = new javax.swing.JLabel();
        pn_brgmasuk = new javax.swing.JPanel();
        Label_brgmasuk = new javax.swing.JLabel();
        pn_brgkeluar = new javax.swing.JPanel();
        Label_brgkeluar = new javax.swing.JLabel();
        pn_supplier = new javax.swing.JPanel();
        Label_supplier = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Border = new javax.swing.JPanel();
        Main_Menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_brg = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Cetak_StokBarang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar.setPreferredSize(new java.awt.Dimension(230, 600));

        pn_profil.setBackground(new java.awt.Color(155, 169, 255));
        pn_profil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_profil.setPreferredSize(new java.awt.Dimension(170, 70));
        pn_profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_profilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_profilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_profilMouseExited(evt);
            }
        });

        Label_profil.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_profil.setForeground(new java.awt.Color(255, 255, 255));
        Label_profil.setText("PROFIL");

        javax.swing.GroupLayout pn_profilLayout = new javax.swing.GroupLayout(pn_profil);
        pn_profil.setLayout(pn_profilLayout);
        pn_profilLayout.setHorizontalGroup(
            pn_profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_profilLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Label_profil)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pn_profilLayout.setVerticalGroup(
            pn_profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_profilLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Label_profil)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pn_brgmasuk.setBackground(new java.awt.Color(155, 169, 255));
        pn_brgmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_brgmasuk.setPreferredSize(new java.awt.Dimension(170, 70));
        pn_brgmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_brgmasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_brgmasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_brgmasukMouseExited(evt);
            }
        });

        Label_brgmasuk.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_brgmasuk.setForeground(new java.awt.Color(255, 255, 255));
        Label_brgmasuk.setText("BARANG MASUK");

        javax.swing.GroupLayout pn_brgmasukLayout = new javax.swing.GroupLayout(pn_brgmasuk);
        pn_brgmasuk.setLayout(pn_brgmasukLayout);
        pn_brgmasukLayout.setHorizontalGroup(
            pn_brgmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_brgmasukLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Label_brgmasuk)
                .addGap(28, 28, 28))
        );
        pn_brgmasukLayout.setVerticalGroup(
            pn_brgmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_brgmasukLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(Label_brgmasuk)
                .addGap(26, 26, 26))
        );

        pn_brgkeluar.setBackground(new java.awt.Color(155, 169, 255));
        pn_brgkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_brgkeluar.setPreferredSize(new java.awt.Dimension(170, 70));
        pn_brgkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_brgkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_brgkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_brgkeluarMouseExited(evt);
            }
        });

        Label_brgkeluar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_brgkeluar.setForeground(new java.awt.Color(255, 255, 255));
        Label_brgkeluar.setText("BARANG KELUAR");

        javax.swing.GroupLayout pn_brgkeluarLayout = new javax.swing.GroupLayout(pn_brgkeluar);
        pn_brgkeluar.setLayout(pn_brgkeluarLayout);
        pn_brgkeluarLayout.setHorizontalGroup(
            pn_brgkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_brgkeluarLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(Label_brgkeluar)
                .addGap(25, 25, 25))
        );
        pn_brgkeluarLayout.setVerticalGroup(
            pn_brgkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_brgkeluarLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(Label_brgkeluar)
                .addGap(26, 26, 26))
        );

        pn_supplier.setBackground(new java.awt.Color(155, 169, 255));
        pn_supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_supplier.setPreferredSize(new java.awt.Dimension(170, 70));
        pn_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_supplierMouseExited(evt);
            }
        });

        Label_supplier.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_supplier.setForeground(new java.awt.Color(255, 255, 255));
        Label_supplier.setText("DATA SUPPLIER");

        javax.swing.GroupLayout pn_supplierLayout = new javax.swing.GroupLayout(pn_supplier);
        pn_supplier.setLayout(pn_supplierLayout);
        pn_supplierLayout.setHorizontalGroup(
            pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_supplierLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(Label_supplier)
                .addGap(31, 31, 31))
        );
        pn_supplierLayout.setVerticalGroup(
            pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_supplierLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(Label_supplier)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_brgkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_brgmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(pn_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_brgmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_brgkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Menu.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(155, 169, 255));
        Header.setPreferredSize(new java.awt.Dimension(794, 120));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        Menu.add(Header, java.awt.BorderLayout.PAGE_START);

        Border.setBackground(new java.awt.Color(255, 255, 255));
        Border.setPreferredSize(new java.awt.Dimension(802, 488));

        Main_Menu.setBackground(new java.awt.Color(155, 169, 255));

        tabel_brg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tabel_brg.setForeground(new java.awt.Color(35, 35, 35));
        tabel_brg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Kategori", "Jumlah Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_brg.setRowHeight(30);
        jScrollPane1.setViewportView(tabel_brg);

        javax.swing.GroupLayout Main_MenuLayout = new javax.swing.GroupLayout(Main_Menu);
        Main_Menu.setLayout(Main_MenuLayout);
        Main_MenuLayout.setHorizontalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        Main_MenuLayout.setVerticalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_MenuLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout BorderLayout = new javax.swing.GroupLayout(Border);
        Border.setLayout(BorderLayout);
        BorderLayout.setHorizontalGroup(
            BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Main_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        BorderLayout.setVerticalGroup(
            BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Main_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Menu.add(Border, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Cetak Laporan");

        Cetak_StokBarang.setText("STOK BARANG");
        Cetak_StokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cetak_StokBarangActionPerformed(evt);
            }
        });
        jMenu1.add(Cetak_StokBarang);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cetak_StokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cetak_StokBarangActionPerformed
        try {
            File namaFile = new File("src/LAPORAN/STOK_BARANG.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namaFile.getPath(), null, KONEKSI.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_Cetak_StokBarangActionPerformed

    private void pn_profilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_profilMouseClicked
        new PROFIL().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_profilMouseClicked

    private void pn_profilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_profilMouseEntered
        pn_profil.setBackground(new Color(66, 87, 215));
    }//GEN-LAST:event_pn_profilMouseEntered

    private void pn_profilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_profilMouseExited
        pn_profil.setBackground(new Color(155, 169, 255));
    }//GEN-LAST:event_pn_profilMouseExited

    private void pn_brgmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_brgmasukMouseClicked
        new BARANG_MASUK().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_brgmasukMouseClicked

    private void pn_brgmasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_brgmasukMouseEntered
        pn_brgmasuk.setBackground(new Color(66, 87, 215));
    }//GEN-LAST:event_pn_brgmasukMouseEntered

    private void pn_brgmasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_brgmasukMouseExited
        pn_brgmasuk.setBackground(new Color(155, 169, 255));
    }//GEN-LAST:event_pn_brgmasukMouseExited

    private void pn_brgkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_brgkeluarMouseClicked
        new BARANG_KELUAR().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_brgkeluarMouseClicked

    private void pn_brgkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_brgkeluarMouseEntered
        pn_brgkeluar.setBackground(new Color(66, 87, 215));
    }//GEN-LAST:event_pn_brgkeluarMouseEntered

    private void pn_brgkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_brgkeluarMouseExited
        pn_brgkeluar.setBackground(new Color(155, 169, 255));
    }//GEN-LAST:event_pn_brgkeluarMouseExited

    private void pn_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_supplierMouseClicked
        new SUPPLIER().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pn_supplierMouseClicked

    private void pn_supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_supplierMouseEntered
        pn_supplier.setBackground(new Color(66, 87, 215));
    }//GEN-LAST:event_pn_supplierMouseEntered

    private void pn_supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_supplierMouseExited
        pn_supplier.setBackground(new Color(155, 169, 255));
    }//GEN-LAST:event_pn_supplierMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DASHBOARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Border;
    private javax.swing.JMenuItem Cetak_StokBarang;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Label_brgkeluar;
    private javax.swing.JLabel Label_brgmasuk;
    private javax.swing.JLabel Label_profil;
    private javax.swing.JLabel Label_supplier;
    private javax.swing.JPanel Main_Menu;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_brgkeluar;
    private javax.swing.JPanel pn_brgmasuk;
    private javax.swing.JPanel pn_profil;
    private javax.swing.JPanel pn_supplier;
    private javax.swing.JTable tabel_brg;
    // End of variables declaration//GEN-END:variables
}
