/**
 * @author Kelompok 2 - R6P
 */

package GUI;
import SYNTAX.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class LOGIN extends javax.swing.JFrame {

    public LOGIN() {
        initComponents();
        this.setLocationRelativeTo(null);

        tampilLogo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        PanelLogin = new javax.swing.JLabel();
        Label_username = new javax.swing.JLabel();
        input_usn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Label_Password = new javax.swing.JLabel();
        input_pass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        button_login = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Label_register = new javax.swing.JLabel();
        Main_Menu = new javax.swing.JPanel();
        label_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar.setPreferredSize(new java.awt.Dimension(300, 600));

        PanelLogin.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        PanelLogin.setForeground(new java.awt.Color(255, 255, 255));
        PanelLogin.setText("LOGIN");

        Label_username.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_username.setForeground(new java.awt.Color(255, 255, 255));
        Label_username.setText("Username");

        input_usn.setBackground(new java.awt.Color(43, 57, 144));
        input_usn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        input_usn.setForeground(new java.awt.Color(255, 255, 255));
        input_usn.setBorder(null);

        Label_Password.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_Password.setForeground(new java.awt.Color(255, 255, 255));
        Label_Password.setText("Password");

        input_pass.setBackground(new java.awt.Color(43, 57, 144));
        input_pass.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        input_pass.setForeground(new java.awt.Color(255, 255, 255));
        input_pass.setBorder(null);

        button_login.setBackground(new java.awt.Color(155, 169, 255));
        button_login.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        button_login.setForeground(new java.awt.Color(255, 255, 255));
        button_login.setText("LOGIN");
        button_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        button_cancel.setBackground(new java.awt.Color(255, 102, 102));
        button_cancel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        button_cancel.setText("CANCEL");
        button_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Don't Have an Account?");

        Label_register.setBackground(new java.awt.Color(255, 255, 255));
        Label_register.setForeground(new java.awt.Color(0, 135, 255));
        Label_register.setText("Register Now!");
        Label_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_registerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label_register))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PanelLogin)
                                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_username)
                                    .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(input_pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(Label_Password)
                                        .addComponent(jSeparator1)
                                        .addComponent(input_usn)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(PanelLogin)
                .addGap(43, 43, 43)
                .addComponent(Label_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_usn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Label_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_register)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Main_Menu.setBackground(new java.awt.Color(155, 169, 255));

        javax.swing.GroupLayout Main_MenuLayout = new javax.swing.GroupLayout(Main_Menu);
        Main_Menu.setLayout(Main_MenuLayout);
        Main_MenuLayout.setHorizontalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(label_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        Main_MenuLayout.setVerticalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(label_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        getContentPane().add(Main_Menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilLogo() {

        ImageIcon icon = new ImageIcon(
                getClass().getResource("/ASSETS/Logo_Hamada.png"));

        Image img = icon.getImage().getScaledInstance(
                label_Logo.getWidth(),
                label_Logo.getHeight(),
                Image.SCALE_SMOOTH);

        label_Logo.setIcon(new ImageIcon(img));
    }
    
    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        String username = input_usn.getText();
        String password = new String(input_pass.getPassword());
        
        boolean log = USER.login(username, password);
        
        if (log){
            DASHBOARD board = new DASHBOARD();
            board.setVisible(true);
            board.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_button_loginActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        if (input_usn.getText().isEmpty() && input_pass.getText().isEmpty()){
            
            // Jika inputan kosong, konfirmasi untuk keluar
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Apakah anda yakin ingin keluar?",
                    "Konfirmasi keluar", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        } else {
            input_usn.setText("");
            input_pass.setText("");
        }
    }//GEN-LAST:event_button_cancelActionPerformed

    private void Label_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_registerMouseClicked
        REGISTER createAcc = new REGISTER();
        createAcc.setVisible(true);
        createAcc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Label_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LOGIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_register;
    private javax.swing.JLabel Label_username;
    private javax.swing.JPanel Main_Menu;
    private javax.swing.JLabel PanelLogin;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_login;
    private javax.swing.JPasswordField input_pass;
    private javax.swing.JTextField input_usn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_Logo;
    // End of variables declaration//GEN-END:variables
}
