/**
 * @author Kelompok 2 - R6P
 */

package GUI;

import SYNTAX.USER;
import javax.swing.JOptionPane;

public class PROFIL extends javax.swing.JFrame {
    DASHBOARD db = new DASHBOARD();
    
    public PROFIL() {
        initComponents();
        this.setLocationRelativeTo(null);
        
         
        if (USER.currentUsn == null) {
            LOGIN login = new LOGIN();
            login.setLocationRelativeTo(null);
            login.setVisible(true);

            this.dispose();
            return;
        }
        
        tampil_usn.setText(USER.currentUsn);
        tampil_namalengkap.setText(USER.currentUser);
        tampil_jabatan.setText(USER.currentJabatan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        btn_LOGOUT = new javax.swing.JButton();
        Label_profil = new javax.swing.JLabel();
        Main_Menu = new javax.swing.JPanel();
        btn_BACK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Label_usn = new javax.swing.JLabel();
        tampil_usn = new javax.swing.JLabel();
        Label_namalengkap = new javax.swing.JLabel();
        tampil_namalengkap = new javax.swing.JLabel();
        Label_jabatan = new javax.swing.JLabel();
        tampil_jabatan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar.setPreferredSize(new java.awt.Dimension(300, 600));

        btn_LOGOUT.setBackground(new java.awt.Color(255, 50, 50));
        btn_LOGOUT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        btn_LOGOUT.setText("LOGOUT");
        btn_LOGOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LOGOUTActionPerformed(evt);
            }
        });

        Label_profil.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Label_profil.setForeground(new java.awt.Color(255, 255, 255));
        Label_profil.setText("PROFIL");

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Label_profil))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btn_LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(Label_profil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addComponent(btn_LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Main_Menu.setBackground(new java.awt.Color(155, 169, 255));

        btn_BACK.setBackground(new java.awt.Color(43, 57, 144));
        btn_BACK.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_BACK.setForeground(new java.awt.Color(255, 255, 255));
        btn_BACK.setText("BACK");
        btn_BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BACKActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(43, 57, 144));

        Label_usn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Label_usn.setForeground(new java.awt.Color(255, 255, 255));
        Label_usn.setText("Username:");

        tampil_usn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tampil_usn.setForeground(new java.awt.Color(255, 255, 255));

        Label_namalengkap.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Label_namalengkap.setForeground(new java.awt.Color(255, 255, 255));
        Label_namalengkap.setText("Nama Lengkap:");

        tampil_namalengkap.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tampil_namalengkap.setForeground(new java.awt.Color(255, 255, 255));

        Label_jabatan.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Label_jabatan.setForeground(new java.awt.Color(255, 255, 255));
        Label_jabatan.setText("Jabatan:");

        tampil_jabatan.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tampil_jabatan.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_namalengkap)
                    .addComponent(Label_usn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_jabatan, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tampil_usn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampil_namalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampil_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_usn)
                    .addComponent(tampil_usn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_namalengkap)
                    .addComponent(tampil_namalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_jabatan)
                    .addComponent(tampil_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout Main_MenuLayout = new javax.swing.GroupLayout(Main_Menu);
        Main_Menu.setLayout(Main_MenuLayout);
        Main_MenuLayout.setHorizontalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_MenuLayout.createSequentialGroup()
                        .addComponent(btn_BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_MenuLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        Main_MenuLayout.setVerticalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142)
                .addComponent(btn_BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        getContentPane().add(Main_Menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BACKActionPerformed
        DASHBOARD db = new DASHBOARD();
        db.setLocationRelativeTo(null);
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BACKActionPerformed

    private void btn_LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LOGOUTActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {

            USER.logout();      

            LOGIN login = new LOGIN();
            login.setLocationRelativeTo(null);
            login.setVisible(true);

            this.dispose();     
        }
    }//GEN-LAST:event_btn_LOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROFIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROFIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROFIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROFIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROFIL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_jabatan;
    private javax.swing.JLabel Label_namalengkap;
    private javax.swing.JLabel Label_profil;
    private javax.swing.JLabel Label_usn;
    private javax.swing.JPanel Main_Menu;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JButton btn_BACK;
    private javax.swing.JButton btn_LOGOUT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tampil_jabatan;
    private javax.swing.JLabel tampil_namalengkap;
    private javax.swing.JLabel tampil_usn;
    // End of variables declaration//GEN-END:variables
}
