/**
 * @author Kelompok 2 - R6P
 */

package GUI;
import javax.swing.JOptionPane;
import SYNTAX.*;

public class REGISTER extends javax.swing.JFrame {

    public REGISTER() {
        initComponents();
        
        // Tampil LOGO
        LOGO.setIconResize(label_Logo, "Logo_Hamada.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Sidebar = new javax.swing.JPanel();
        PanelRegister = new javax.swing.JLabel();
        Label_nama = new javax.swing.JLabel();
        input_nama = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Label_jabatan = new javax.swing.JLabel();
        radio_admin = new javax.swing.JRadioButton();
        radio_staff = new javax.swing.JRadioButton();
        Label_username = new javax.swing.JLabel();
        input_usn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Label_password = new javax.swing.JLabel();
        input_pass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        button_register = new javax.swing.JButton();
        Main_Menu = new javax.swing.JPanel();
        label_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar.setPreferredSize(new java.awt.Dimension(300, 600));

        PanelRegister.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        PanelRegister.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegister.setText("REGISTER");

        Label_nama.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_nama.setForeground(new java.awt.Color(255, 255, 255));
        Label_nama.setText("Nama Lengkap");

        input_nama.setBackground(new java.awt.Color(43, 57, 144));
        input_nama.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        input_nama.setForeground(new java.awt.Color(255, 255, 255));
        input_nama.setBorder(null);

        Label_jabatan.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_jabatan.setForeground(new java.awt.Color(255, 255, 255));
        Label_jabatan.setText("Jabatan");

        buttonGroup1.add(radio_admin);
        radio_admin.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        radio_admin.setForeground(new java.awt.Color(255, 255, 255));
        radio_admin.setText("Admin");

        buttonGroup1.add(radio_staff);
        radio_staff.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        radio_staff.setForeground(new java.awt.Color(255, 255, 255));
        radio_staff.setText("Staff");

        Label_username.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_username.setForeground(new java.awt.Color(255, 255, 255));
        Label_username.setText("Username");

        input_usn.setBackground(new java.awt.Color(43, 57, 144));
        input_usn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        input_usn.setForeground(new java.awt.Color(255, 255, 255));
        input_usn.setBorder(null);

        Label_password.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_password.setForeground(new java.awt.Color(255, 255, 255));
        Label_password.setText("Password");

        input_pass.setBackground(new java.awt.Color(43, 57, 144));
        input_pass.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        input_pass.setForeground(new java.awt.Color(255, 255, 255));
        input_pass.setBorder(null);

        button_register.setBackground(new java.awt.Color(155, 169, 255));
        button_register.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        button_register.setForeground(new java.awt.Color(255, 255, 255));
        button_register.setText("SIGN UP");
        button_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                                    .addComponent(Label_nama)
                                    .addGap(65, 65, 65))
                                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_pass)
                                    .addComponent(input_nama)
                                    .addGroup(SidebarLayout.createSequentialGroup()
                                        .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_password)
                                            .addComponent(Label_jabatan)
                                            .addComponent(Label_username)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(input_usn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                                                .addComponent(button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SidebarLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(radio_admin)
                                .addGap(57, 57, 57)
                                .addComponent(radio_staff))))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(PanelRegister)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PanelRegister)
                .addGap(47, 47, 47)
                .addComponent(Label_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Label_jabatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_admin)
                    .addComponent(radio_staff))
                .addGap(31, 31, 31)
                .addComponent(Label_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_usn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Main_Menu.setBackground(new java.awt.Color(155, 169, 255));

        label_Logo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        label_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Main_MenuLayout = new javax.swing.GroupLayout(Main_Menu);
        Main_Menu.setLayout(Main_MenuLayout);
        Main_MenuLayout.setHorizontalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(label_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        Main_MenuLayout.setVerticalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_MenuLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(label_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        getContentPane().add(Main_Menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        String username = input_usn.getText();
        String password = new String(input_pass.getPassword());
        String nama_lengkap = input_nama.getText();
        String jabatan = "";

        if(radio_admin.isSelected()) {
            jabatan = "Admin Hamada";
        } else if(radio_staff.isSelected()) {
            jabatan = "Staff";
        }
        
        if (!username.isEmpty() && !nama_lengkap.isEmpty()) {
            boolean Reg = USER.register(username, password, jabatan, nama_lengkap);
            
            if (Reg) {
                JOptionPane.showMessageDialog(this, "Registrasi Berhasil!");

                this.dispose(); // Menutup Form REGISTER

                // Membuka FORM LOGIN
                new LOGIN().setVisible(true); 
                new LOGIN().setLocationRelativeTo(null);                         
            } else {
                JOptionPane.showMessageDialog(this, "Registrasi Gagal! Periksa koneksi database.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Isi semua data terlebih dahulu!");
        }

        
        
    }//GEN-LAST:event_button_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new REGISTER().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_jabatan;
    private javax.swing.JLabel Label_nama;
    private javax.swing.JLabel Label_password;
    private javax.swing.JLabel Label_username;
    private javax.swing.JPanel Main_Menu;
    private javax.swing.JLabel PanelRegister;
    private javax.swing.JPanel Sidebar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_register;
    private javax.swing.JTextField input_nama;
    private javax.swing.JPasswordField input_pass;
    private javax.swing.JTextField input_usn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label_Logo;
    private javax.swing.JRadioButton radio_admin;
    private javax.swing.JRadioButton radio_staff;
    // End of variables declaration//GEN-END:variables
}
