/**
 * @author Kelompok 2 - R6P
 */

package GUI;
import SYNTAX.KONEKSI;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SUPPLIER extends javax.swing.JFrame {
    SYNTAX.SUPPLIER supplier = new SYNTAX.SUPPLIER();
    DASHBOARD db = new DASHBOARD();
    
    public SUPPLIER() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        formatTable();
        refreshTabel();
    }
    
    void formatTable(){
        tabel_barang.setModel(supplier.getModelBarang());
        tabel_barang.getTableHeader().setOpaque(false);
        tabel_barang.getTableHeader().setBackground(new java.awt.Color(43, 57, 144));
        tabel_barang.getTableHeader().setForeground(java.awt.Color.BLACK);
        tabel_barang.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tabel_barang.getTableHeader().setReorderingAllowed(false);
        
        tabel_supplier.setModel(supplier.getModelSupplier());
        tabel_supplier.getTableHeader().setOpaque(false);
        tabel_supplier.getTableHeader().setBackground(new java.awt.Color(43, 57, 144));
        tabel_supplier.getTableHeader().setForeground(java.awt.Color.BLACK);
        tabel_supplier.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tabel_supplier.getTableHeader().setReorderingAllowed(false);
    }
    
    public void refreshTabel (){
        tabel_barang.setModel(supplier.getModelBarang());
        tabel_supplier.setModel(supplier.getModelSupplier());
    }
    
    public String generateIdBarang() {
        String newId = "PT001";

        try {
            Connection conn = KONEKSI.getConnection();
            String query = "SELECT id_supplier FROM supplier ORDER BY id_supplier DESC LIMIT 1";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String lastId = rs.getString("id_supplier"); // ex: "BRG004"
                int number = Integer.parseInt(lastId.substring(3)); // ambil angka: 4
                number++; // jadi 5
                newId = String.format("PT%03d", number); // jadi "BRG005"
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    
        return newId;
    }
    
    public void resetData(){
        tampil_idsupplier.setText("");
        tampil_namabrg.setText("");
        nama_supplier.setText("");
        alamat_supplier.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        Label_Supplier = new javax.swing.JLabel();
        Label_idsupplier = new javax.swing.JLabel();
        tampil_idsupplier = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Label_idbrg = new javax.swing.JLabel();
        tampil_namabrg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Label_namasupplier = new javax.swing.JLabel();
        nama_supplier = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Label_alamat = new javax.swing.JLabel();
        alamat_supplier = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btn_ADD = new javax.swing.JButton();
        btn_EDIT = new javax.swing.JButton();
        btn_REMOVE = new javax.swing.JButton();
        Main_Menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_supplier = new javax.swing.JTable();
        btn_BACK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar.setBackground(new java.awt.Color(43, 57, 144));
        Sidebar.setForeground(new java.awt.Color(255, 255, 255));
        Sidebar.setPreferredSize(new java.awt.Dimension(300, 600));

        Label_Supplier.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Label_Supplier.setForeground(new java.awt.Color(255, 255, 255));
        Label_Supplier.setText("DATA SUPPLIER");

        Label_idsupplier.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_idsupplier.setForeground(new java.awt.Color(255, 255, 255));
        Label_idsupplier.setText("ID Supplier");

        tampil_idsupplier.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tampil_idsupplier.setForeground(new java.awt.Color(255, 255, 255));

        Label_idbrg.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_idbrg.setForeground(new java.awt.Color(255, 255, 255));
        Label_idbrg.setText("Nama Barang");

        tampil_namabrg.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tampil_namabrg.setForeground(new java.awt.Color(255, 255, 255));

        Label_namasupplier.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_namasupplier.setForeground(new java.awt.Color(255, 255, 255));
        Label_namasupplier.setText("Nama Supplier");

        nama_supplier.setBackground(new java.awt.Color(43, 57, 144));
        nama_supplier.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        nama_supplier.setForeground(new java.awt.Color(255, 255, 255));
        nama_supplier.setBorder(null);

        Label_alamat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Label_alamat.setForeground(new java.awt.Color(255, 255, 255));
        Label_alamat.setText("Alamat");

        alamat_supplier.setBackground(new java.awt.Color(43, 57, 144));
        alamat_supplier.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        alamat_supplier.setForeground(new java.awt.Color(255, 255, 255));
        alamat_supplier.setBorder(null);

        btn_ADD.setBackground(new java.awt.Color(155, 169, 255));
        btn_ADD.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_ADD.setForeground(new java.awt.Color(255, 255, 255));
        btn_ADD.setText("ADD");
        btn_ADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ADDActionPerformed(evt);
            }
        });

        btn_EDIT.setBackground(new java.awt.Color(155, 169, 255));
        btn_EDIT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_EDIT.setForeground(new java.awt.Color(255, 255, 255));
        btn_EDIT.setText("EDIT");
        btn_EDIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EDITActionPerformed(evt);
            }
        });

        btn_REMOVE.setBackground(new java.awt.Color(255, 102, 102));
        btn_REMOVE.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_REMOVE.setForeground(new java.awt.Color(255, 255, 255));
        btn_REMOVE.setText("REMOVE");
        btn_REMOVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_REMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_REMOVEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_alamat)
                            .addComponent(alamat_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_namasupplier)
                            .addComponent(nama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Label_idbrg)
                                .addComponent(tampil_namabrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tampil_idsupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Label_idsupplier))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addComponent(btn_ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btn_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Label_Supplier))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btn_REMOVE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Label_Supplier)
                .addGap(37, 37, 37)
                .addComponent(Label_idsupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tampil_idsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_idbrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tampil_namabrg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_namasupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamat_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_REMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Main_Menu.setBackground(new java.awt.Color(155, 169, 255));
        Main_Menu.setForeground(new java.awt.Color(255, 255, 255));

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang"
            }
        ));
        tabel_barang.setRowHeight(30);
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_barang);

        tabel_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Supplier", "Nama Supplier", "Nama Barang", "Alamat"
            }
        ));
        tabel_supplier.setRowHeight(30);
        tabel_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_supplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_supplier);
        if (tabel_supplier.getColumnModel().getColumnCount() > 0) {
            tabel_supplier.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_BACK.setBackground(new java.awt.Color(43, 57, 144));
        btn_BACK.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_BACK.setForeground(new java.awt.Color(255, 255, 255));
        btn_BACK.setText("BACK");
        btn_BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BACKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Barang");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Supplier");

        javax.swing.GroupLayout Main_MenuLayout = new javax.swing.GroupLayout(Main_Menu);
        Main_Menu.setLayout(Main_MenuLayout);
        Main_MenuLayout.setHorizontalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_MenuLayout.createSequentialGroup()
                        .addGroup(Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                            .addGroup(Main_MenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))
                    .addGroup(Main_MenuLayout.createSequentialGroup()
                        .addGroup(Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Main_MenuLayout.setVerticalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(btn_BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(Main_Menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        int baris = tabel_barang.getSelectedRow();
    
        tampil_namabrg.setText(tabel_barang.getValueAt(baris, 1).toString());
        
        tampil_idsupplier.setText("");
        nama_supplier.setText("");
        alamat_supplier.setText("");
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void tabel_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_supplierMouseClicked
        int baris = tabel_supplier.getSelectedRow();
    
        tampil_idsupplier.setText(tabel_supplier.getValueAt(baris, 0).toString());
        nama_supplier.setText(tabel_supplier.getValueAt(baris, 1).toString());
        tampil_namabrg.setText(tabel_supplier.getValueAt(baris, 2).toString());
        alamat_supplier.setText(tabel_supplier.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tabel_supplierMouseClicked

    private void btn_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ADDActionPerformed
        int baris = tabel_barang.getSelectedRow();
        
        String id = generateIdBarang();
        String nama = nama_supplier.getText();
        String barang = tampil_namabrg.getText();
        String alamat = alamat_supplier.getText();

        if (!nama.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) tabel_supplier.getModel();
            DefaultTableModel model_brg = (DefaultTableModel) tabel_barang.getModel();
            boolean add = supplier.input(id, nama, barang, alamat);
            
            if (add){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan ke Tabel!");
                model.addRow(new Object[]{id, nama, barang, alamat});
                model_brg.removeRow(baris);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal Menyimpan ke Database");
            }
            
            resetData();
        } else {
            JOptionPane.showMessageDialog(this, "Isi Nama Barang terlebih dahulu!");
        }
    }//GEN-LAST:event_btn_ADDActionPerformed

    private void btn_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BACKActionPerformed
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BACKActionPerformed

    private void btn_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EDITActionPerformed
        int selectedRow = tabel_supplier.getSelectedRow();
        
        String id = tabel_supplier.getValueAt(selectedRow, 0).toString();            
        String namaBarang = tampil_namabrg.getText();
        String namaSupplier = nama_supplier.getText();
        String alamat = alamat_supplier.getText();

        if(selectedRow != -1){
            boolean isUpdated = supplier.edit(id, namaBarang, namaSupplier, alamat);
                
            if(isUpdated){   
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                refreshTabel();
                resetData();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data di database!");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris di tabel yang ingin diubah terlebih dahulu");
        }
    }//GEN-LAST:event_btn_EDITActionPerformed

    private void btn_REMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_REMOVEActionPerformed
         int selectedRow = tabel_supplier.getSelectedRow();

        if (selectedRow != -1){
            String id = tabel_supplier.getValueAt(selectedRow, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin ingin menghapus supplier dengan ID " + id + "?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if(confirm == JOptionPane.YES_OPTION){
                boolean isDeleted = supplier.delete(id);

                if (isDeleted){
                    DefaultTableModel model_supplier = (DefaultTableModel) tabel_supplier.getModel();
                    model_supplier.removeRow(selectedRow);

                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    resetData();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data dari database!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris di tabel yang ingin di hapus terlebih dahulu!");
        }
    }//GEN-LAST:event_btn_REMOVEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SUPPLIER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SUPPLIER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SUPPLIER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SUPPLIER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SUPPLIER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Supplier;
    private javax.swing.JLabel Label_alamat;
    private javax.swing.JLabel Label_idbrg;
    private javax.swing.JLabel Label_idsupplier;
    private javax.swing.JLabel Label_namasupplier;
    private javax.swing.JPanel Main_Menu;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JTextField alamat_supplier;
    private javax.swing.JButton btn_ADD;
    private javax.swing.JButton btn_BACK;
    private javax.swing.JButton btn_EDIT;
    private javax.swing.JButton btn_REMOVE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nama_supplier;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTable tabel_supplier;
    private javax.swing.JLabel tampil_idsupplier;
    private javax.swing.JLabel tampil_namabrg;
    // End of variables declaration//GEN-END:variables
}
